apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: arc-rabbit-mq
  namespace: arc-rabbit-mq
spec:
  releaseName: arc-rabbit-mq
  chart:
    git: https://github.com/chzbrgr71/arc-helm-demo
    ref: master
    path: charts/rabbit-mq
#  values:
#    serviceName: arc-k8s-demo
#    auth.username: admin
#    auth.password: secretpassword